name: 'LensDX Deployment Action'
description: 'Conveniently create a deployment event in LensDX'
branding:
  icon: 'bar-chart-2'
  color: 'black'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/deployment.sh
      shell: bash